Mathbox/Mathbox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("web.urls", namespace="web"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Mathbox/web/urls.py
from django.urls import path
from web.views import index, doc, exercises, games, community, tools, community_post, exercise, game, tool


app_name = "web"

urlpatterns = [
    path("",index, name="index"),
    path("documentation/", doc, name="documentation"),
    path("exercises/", exercises, name="exercises"),
    path('exercises/<str:about_text>/', exercise, name='exercise'),
    path("games/", games, name="games"),
    path('games/<str:name_text>/', game, name='game'),
    path("community/", community, name="community"),
    path("tools/", tools, name="tools"),
    path('tools/<str:name_text>/', tool, name='tool'),
    path("community_post/", community_post, name="community_post")
]

Mathbox/web/models.py
from django.db import models


CATEGORY = (
    ("1", "Kids"),
    ("2", "Students"),
    ("3", "Both")
)


class Faq(models.Model):
    question = models.CharField(max_length=270)
    answer = models.TextField()

    def __str__(self):
        return self.question
    

class CommmunityPost(models.Model):
    heading = models.CharField(max_length=270, blank=True, null=True)
    image = models.ImageField(upload_to="community_post/", blank=True, null=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content
    

class Exercises(models.Model):
    about = models.CharField(max_length=270)
    css = models.TextField(verbose_name="CSS Code")
    js = models.TextField(verbose_name="JavaScript Code")
    html = models.TextField(verbose_name="HTML Code")
    type = models.CharField(max_length=270, choices=CATEGORY)

    def __str__(self):
        return self.about
    

class Games(models.Model):
    name = models.CharField(max_length=270)
    image = models.ImageField(upload_to="game_images/")
    type = models.CharField(max_length=270, choices=CATEGORY)
    css = models.TextField(verbose_name="CSS Code")
    js = models.TextField(verbose_name="JavaScript Code")
    html = models.TextField(verbose_name="HTML Code")

    def __str__(self):
        return self.name


class Tools(models.Model):
    name = models.CharField(max_length=270)
    html = models.TextField(verbose_name="HTML code")
    css = models.TextField(verbose_name="CSS Code")
    js = models.TextField(verbose_name="JavaScript Code")

    def __str__(self):
        return self.name
    

class Kids(models.Model):
    title = models.CharField(max_length=270)
    content = models.TextField()
    item = models.CharField(max_length=270)

    def __str__(self):
        return self.title
    
class KidsPlay(models.Model):
    kids = models.ForeignKey('Kids', on_delete=models.CASCADE, related_name='plays')
    value = models.CharField(max_length=270, blank=True, null=True)
    link = models.CharField(max_length=270, blank=True, null=True)


class Student(models.Model):
    title = models.CharField(max_length=270)
    content = models.TextField()
    item = models.CharField(max_length=270)

    def __str__(self):
        return self.title
    
class StudentPlay(models.Model):
    kids = models.ForeignKey('Student', on_delete=models.CASCADE, related_name='plays')
    value = models.CharField(max_length=270, blank=True, null=True)
    link = models.CharField(max_length=270, blank=True, null=True)

Mathbox/web/forms.py
# forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content', 'image', 'heading']

Mathbox/web/views.py
from django.shortcuts import render, redirect, get_object_or_404
from urllib.parse import unquote
from django.http.response import HttpResponse
from web.models import Faq, CommmunityPost, Exercises, Games, Tools, Kids, Student
from django.urls import reverse


def index(request):
    faqs = Faq.objects.all()
    context = {
        "faqs": faqs,
    }
    return render(request, "index.html", context=context)

def doc(request):
    contents = Kids.objects.all()
    students = Student.objects.all()
    if 'search' in request.GET:
        search_term = request.GET['search'].lower()
        contents = sorted(contents, 
                      key=lambda x: search_term in x.title.lower(), 
                      reverse=True)
    if 'search' in request.GET:
        search_term = request.GET['search'].lower()
        contents = sorted(contents, 
                      key=lambda x: search_term in x.item.lower(), 
                      reverse=True)
    if 'search' in request.GET:
        search_term = request.GET['search'].lower()
        students = sorted(students, 
                      key=lambda x: search_term in x.title.lower(), 
                      reverse=True)
    if 'search' in request.GET:
        search_term = request.GET['search'].lower()
        students = sorted(students, 
                      key=lambda x: search_term in x.item.lower(),
                      reverse=True)
    context = {
        "contents": contents,
        "students": students,
    }
    return render(request, "doc.html", context=context)

def exercises(request):
    contents = Exercises.objects.all()
    if 'search' in request.GET:
        search_term = request.GET['search'].lower()
        contents = sorted(contents, 
                      key=lambda x: search_term in x.about.lower(), 
                      reverse=True)
    context = {
        "contents": contents,
    }
    return render(request, "exercise.html", context=context)


def exercise(request, about_text):
    decoded_about = unquote(about_text)
    exercises = get_object_or_404(Exercises, about=decoded_about)
    return render(request, 'exercises.html', {'exercises': exercises})


def games(request):
    contents = Games.objects.all()
    if 'search' in request.GET:
        search_term = request.GET['search'].lower()
        contents = sorted(contents, 
                      key=lambda x: search_term in x.name.lower(), 
                      reverse=True)
    context = {
        "contents": contents,
    }
    return render(request, "games.html", context=context)


def game(request, name_text):
    decoded_name = unquote(name_text)
    game = get_object_or_404(Games, name=decoded_name)
    return render(request, 'game.html', {'game': game})


def community(request):
    posts = CommmunityPost.objects.all().order_by('-created_at')
    if 'search' in request.GET:
        search_term = request.GET['search'].lower()
        posts = sorted(posts, 
                      key=lambda x: search_term in x.content.lower(), 
                      reverse=True)
    context = {
        "posts" : posts
    }
    return render(request, "community.html", context=context)

def tools(request):
    contents = Tools.objects.all()
    if 'search' in request.GET:
        search_term = request.GET['search'].lower()
        contents = sorted(contents, 
                      key=lambda x: search_term in x.name.lower(), 
                      reverse=True)
    context = {
        "contents": contents,
    }
    return render(request, "tools.html", context=context)


def tool(request, name_text):
    decoded_name = unquote(name_text)
    tool = get_object_or_404(Tools, name=decoded_name)
    return render(request, 'tool.html', {'tool': tool})


def community_post(request):
    heading = request.POST.get("heading")
    image = request.FILES.get("image")
    content = request.POST.get("content")

    CommmunityPost.objects.create(
        heading = heading,
        image = image,
        content = content,
    )

    return redirect(reverse("web:community"))

Mathbox/templates/community.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static './images/favicon.ico' %}"/>
    <title>MathBox-Community</title>
    <link rel="stylesheet" href="{% static './css/style.css' %}">
    <script src="{% static './js/script.js' %}" defer></script>
</head>
<body>
    <header>
      <img src="{% static './images/menu.svg' %}" alt="" id="menu"/>
        <h1>
            <a href="#">
                <img src="{% static './images/logo-text.svg' %}" alt=""/>
            </a>
        </h1>
        <nav>
            <ul>
                <li><a href="{% url 'web:index' %}">Home</a></li>
                <li><a href="{% url 'web:documentation' %}">Documentation</a></li>
                <li><a href="{% url 'web:exercises' %}">Exercises</a></li>
                <li><a href="{% url 'web:games' %}">Games</a></li>
                <li><a href="{% url 'web:community' %}">Community</a></li>
                <li><a href="{% url 'web:tools' %}">Tools</a></li>
            </ul>
        </nav>
        <ul>
            <li>
                <div class="form">
                    <input type="search" placeholder="Search..." id="communitySearch"/>
                    <img src="{% static './images/search.svg' %}" alt=""/>
                </div>
            </li>
        </ul>
    </header>
    <div id="nav" class="overlay">
      <a href="javascript:void(0)" class="closebtn" id="close">&times;</a>
      <div class="overlay-content">
          <a href="{% url 'web:index' %}">Home</a>
          <a href="{% url 'web:documentation' %}">Documentation</a>
          <a href="{% url 'web:exercises' %}">Exercises</a>
          <a href="{% url 'web:games' %}">Games</a>
          <a href="{% url 'web:community' %}">Community</a>
          <a href="{% url 'web:tools' %}">Tools</a>
      </div>
    </div>
    <section class="community">
        <section class="wrapper">
          <h1 style="color: teal;font-size: 55px;text-align: center;">Our Community</h1>
          <div class="post_container">
            <div id="posts">
              {% for post in posts %}
              <div class="community-card" data-name="{{ post.content|lower }}">
                <h4 style="text-align: right;color: #999;font-size: 15px;">{{post.created_at}}</h4>
                {% if post.heading %}
                  <h2 id="head">{{post.heading}}</h2>
                {% endif %}
                {% if post.image %}  
                  <img src="{{post.image.url}}" alt="" id="images">
                {% endif%}
                <p id="content">{{post.content}}</p>
              </div>
              {% endfor %}
            </div>
          </div>
            <form action="{% url 'web:community_post' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form">
                    <input type="file" id="image" accept="image/*" hidden name="image"/>
                    <label for="image">Image (Optional)</label>
                    <input type="text" name="heading" id="heading" placeholder="Your Heading (Optional)" />
                    <textarea id="post" name="content" placeholder="Your Content..."></textarea>
                    <button type="submit" id="submit">Post</button> 
                </div>  
            </form>
        </section>
    </section>
    <footer class="footer">
      <div class="footer-container">
        
        <!-- Branding -->
        <div class="footer-section">
          <img src="{% static './images/logo-text.png' %}" alt=""/>
          <p class="footer-description">
            Explore fun math games, in-depth documentation, interactive exercises, powerful tools, and a friendly community — all in one place.
          </p>
        </div>
  
        <!-- Explore -->
        <div class="footer-section">
          <h3>Explore</h3>
          <ul>
            <li><a href="{% url 'web:games' %}">Math Games</a></li>
            <li><a href="{% url 'web:documentation' %}">Documentation</a></li>
            <li><a href="{% url 'web:exercises' %}">Exercises</a></li>
            <li><a href="{% url 'web:tools' %}">Tools</a></li>
            <li><a href="{% url 'web:community' %}">Community</a></li>
          </ul>
        </div>
  
        <!-- Resources -->
        <div class="footer-section">
          <h3>Resources</h3>
          <ul>
              <li><a href="{% url 'web:index' %}">FAQ</a></li>
              <li><a href="">Contact</a></li>
          </ul>
        </div>
  
        <!-- Connect -->
        <div class="footer-section">
          <h3>Connect</h3>
          <p>Address: Nafil Manzil / Mekkone / Kottamkara / Chandanathope P.O. / Kollam-691014 / Kerala / India</p>
          <p>Email: nafilmnytfj@gmail.com</p>
          <p>Phone Number: +91 9544758339</p>
        </div>
      </div>
      <div class="footer-bottom">
        &copy; 2025 Mathbox. All rights reserved.
      </div>
    </footer>
</body>
</html>

Mathbox/templates/doc.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static './images/favicon.ico' %}"/>
    <title>MathBox-Documentation</title>
    <link rel="stylesheet" href="{% static './css/style.css' %}">
    <script src="{% static './js/script.js' %}" defer></script>
</head>
<body>
    <header>
      <img src="{% static './images/menu.svg' %}" alt="" id="menu"/>
        <h1>
            <a href="#">
                <img src="{% static './images/logo-text.svg' %}" alt=""/>
            </a>
        </h1>
        <nav>
            <ul>
                <li><a href="{% url 'web:index' %}">Home</a></li>
                <li><a href="{% url 'web:documentation' %}">Documentation</a></li>
                <li><a href="{% url 'web:exercises' %}">Exercises</a></li>
                <li><a href="{% url 'web:games' %}">Games</a></li>
                <li><a href="{% url 'web:community' %}">Community</a></li>
                <li><a href="{% url 'web:tools' %}">Tools</a></li>
            </ul>
        </nav>
        <ul>
            <li>
                <div class="form">
                    <input type="search" placeholder="Search..." id="docSearch"/>
                    <img src="{% static './images/search.svg' %}" alt=""/>
                </div>
            </li>
        </ul>
    </header>
    <div id="nav" class="overlay">
      <a href="javascript:void(0)" class="closebtn" id="close">&times;</a>
      <div class="overlay-content">
          <a href="{% url 'web:index' %}">Home</a>
          <a href="{% url 'web:documentation' %}">Documentation</a>
          <a href="{% url 'web:exercises' %}">Exercises</a>
          <a href="{% url 'web:games' %}">Games</a>
          <a href="{% url 'web:community' %}">Community</a>
          <a href="{% url 'web:tools' %}">Tools</a>
      </div>
  </div>
    <section class="document">
        <section class="wrapper">
          <div class="tabs">
            <h1 class="kids" id="kids">For Kids</h1>
            <h1 class="students" id="students">For Students</h1>
          </div>
          <div class="flex">
            <div class="left" id="left">
              {% for content in contents %}
              <div class="kids-card" data-name="{{ content.title }}" data-item="{{ content.item }}">
                <h1>{{content.title}}</h1>
                <p>{{content.content}}</p>
                {% if content.plays %}
                  <div class="flex_button">
                    {% for play in content.plays.all %}
                    <a href="{% url 'web:game' play.link|urlencode %}">{{play.value}}</a>
                    {% endfor %}
                  </div>
                {% endif %}
              </div>
              {% endfor %}
            </div>
            <div class="right" id="right">
              {% for student in students %}
                <div class="students-card" data-name="{{ student.title }}" data-item="{{ student.item }}">
                    <h1>{{student.title}}</h1>
                    <p>{{student.content}}</p>
                    {% if student.plays %}
                      <div class="flex_button">
                        {% for play in student.plays.all %}
                        <a href="{% url 'web:game' play.link|urlencode %}">{{play.value}}</a>
                        {% endfor %}
                      </div>
                    {% endif %}
                </div>
              {% endfor %}
                </div>
            </div>
          </div>
        </section>
    </section>
    <footer class="footer">
      <div class="footer-container">
        
        <!-- Branding -->
        <div class="footer-section">
          <img src="{% static './images/logo-text.png' %}" alt=""/>
          <p class="footer-description">
            Explore fun math games, in-depth documentation, interactive exercises, powerful tools, and a friendly community — all in one place.
          </p>
        </div>
  
        <!-- Explore -->
        <div class="footer-section">
          <h3>Explore</h3>
          <ul>
            <li><a href="{% url 'web:games' %}">Math Games</a></li>
            <li><a href="{% url 'web:documentation' %}">Documentation</a></li>
            <li><a href="{% url 'web:exercises' %}">Exercises</a></li>
            <li><a href="{% url 'web:tools' %}">Tools</a></li>
            <li><a href="{% url 'web:community' %}">Community</a></li>
          </ul>
        </div>
  
        <!-- Resources -->
        <div class="footer-section">
          <h3>Resources</h3>
          <ul>
              <li><a href="{% url 'web:index' %}">FAQ</a></li>
              <li><a href="">Contact</a></li>
          </ul>
        </div>
  
        <!-- Connect -->
        <div class="footer-section">
          <h3>Connect</h3>
          <p>Address: Nafil Manzil / Mekkone / Kottamkara / Chandanathope P.O. / Kollam-691014 / Kerala / India</p>
          <p>Email: nafilmnytfj@gmail.com</p>
          <p>Phone Number: +91 9544758339</p>
        </div>
      </div>
      <div class="footer-bottom">
        &copy; 2025 Mathbox. All rights reserved.
      </div>
    </footer>
</body>
</html>

Mathbox/templates/exercise.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static './images/favicon.ico' %}"/>
    <title>MathBox-Exercises</title>
    <link rel="stylesheet" href="{% static './css/style.css' %}">
    <script src="{% static './js/script.js' %}" defer></script>
</head>
<body>
  <header>
    <img src="{% static './images/menu.svg' %}" alt="" id="menu"/>
    <h1>
        <a href="#">
            <img src="{% static './images/logo-text.svg' %}" alt=""/>
        </a>
    </h1>
    <nav>
        <ul>
            <li><a href="{% url 'web:index' %}">Home</a></li>
            <li><a href="{% url 'web:documentation' %}">Documentation</a></li>
            <li><a href="{% url 'web:exercises' %}">Exercises</a></li>
            <li><a href="{% url 'web:games' %}">Games</a></li>
            <li><a href="{% url 'web:community' %}">Community</a></li></a></li>
            <li><a href="{% url 'web:tools' %}">Tools</a></li>
        </ul>
    </nav>
    <ul>
        <li>
            <div class="form">
                <input type="text" placeholder="Search Exercises..." class="search-input" id="exerciseSearch"/>
                <img src="{% static './images/search.svg' %}" alt=""/>
            </div>
        </li>
    </ul>
  </header>
  <div id="nav" class="overlay">
    <a href="javascript:void(0)" class="closebtn" id="close">&times;</a>
    <div class="overlay-content">
        <a href="{% url 'web:index' %}">Home</a>
        <a href="{% url 'web:documentation' %}">Documentation</a>
        <a href="{% url 'web:exercises' %}">Exercises</a>
        <a href="{% url 'web:games' %}">Games</a>
        <a href="{% url 'web:community' %}">Community</a>
        <a href="{% url 'web:tools' %}">Tools</a>
    </div>
</div>
    <section class="list">
        <section class="wrapper">
            <h1>Here Exercises !</h1>
            <div class="flex" id="exerciseContainer">
              {% for exercise in contents %}
                  <a href="{% url 'web:exercise' exercise.about|urlencode %}" class="exercise-card" data-name="{{ exercise.about|lower }}" style="justify-content: space-between;padding-left: 39px;padding-right: 39px;">
                    <div class="content" style="display: flex;justify-content: center;align-items: center;">
                      <h3 class="about" style="font-size: 39px;">About</h3>
                      <h3 class="sec" style="font-size: 39px;color: teal;border: none;padding: 0px;">{{ exercise.about }}</h3>
                    </div>
                    <h4 class="h4" style="font-size: 19px;color: green;border: green 2px solid;border-radius: 33px;padding: 5px;">{{ exercise.get_type_display }}</h4>
                  </a>
              {% endfor %}
            </div>
        </section>
    </section>
    <footer class="footer">
      <div class="footer-container">
        
        <!-- Branding -->
        <div class="footer-section">
          <img src="{% static './images/logo-text.png' %}" alt=""/>
          <p class="footer-description">
            Explore fun math games, in-depth documentation, interactive exercises, powerful tools, and a friendly community — all in one place.
          </p>
        </div>
  
        <!-- Explore -->
        <div class="footer-section">
          <h3>Explore</h3>
          <ul>
            <li><a href="{% url 'web:games' %}">Math Games</a></li>
            <li><a href="{% url 'web:documentation' %}">Documentation</a></li>
            <li><a href="{% url 'web:exercises' %}">Exercises</a></li>
            <li><a href="{% url 'web:tools' %}">Tools</a></li>
            <li><a href="{% url 'web:community' %}">Community</a></li>
          </ul>
        </div>
  
        <!-- Resources -->
        <div class="footer-section">
          <h3>Resources</h3>
          <ul>
              <li><a href="{% url 'web:index' %}">FAQ</a></li>
              <li><a href="">Contact</a></li>
          </ul>
        </div>
  
        <!-- Connect -->
        <div class="footer-section">
          <h3>Connect</h3>
          <p>Address: Nafil Manzil / Mekkone / Kottamkara / Chandanathope P.O. / Kollam-691014 / Kerala / India</p>
          <p>Email: nafilmnytfj@gmail.com</p>
          <p>Phone Number: +91 9544758339</p>
        </div>
      </div>
      <div class="footer-bottom">
        &copy; 2025 Mathbox. All rights reserved.
      </div>
    </footer>
</body>
</html>

Mathbox/templates/games.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static './images/favicon.ico' %}"/>
    <title>MathBox-Games</title>
    <link rel="stylesheet" href="{% static './css/style.css' %}">
    <script src="{% static './js/script.js' %}" defer></script>
</head>
<body>
    <header>
      <img src="{% static './images/menu.svg' %}" alt="" id="menu"/>
        <h1>
            <a href="#">
                <img src="{% static './images/logo-text.svg' %}" alt=""/>
            </a>
        </h1>
        <nav>
            <ul>
                <li><a href="{% url 'web:index' %}">Home</a></li>
                <li><a href="{% url 'web:documentation' %}">Documentation</a></li>
                <li><a href="{% url 'web:exercises' %}">Exercises</a></li>
                <li><a href="{% url 'web:games' %}">Games</a></li>
                <li><a href="{% url 'web:community' %}">Community</a></li>
                <li><a href="{% url 'web:tools' %}">Tools</a></li>
            </ul>
        </nav>
        <ul>
            <li>
                <div class="form">
                    <input type="text" placeholder="Search Games..." class="search-input" id="gameSearch"/>
                    <img src="{% static './images/search.svg' %}" alt=""/>
                </div>
            </li>
        </ul>
    </header>
    <div id="nav" class="overlay">
      <a href="javascript:void(0)" class="closebtn" id="close">&times;</a>
      <div class="overlay-content">
          <a href="{% url 'web:index' %}">Home</a>
          <a href="{% url 'web:documentation' %}">Documentation</a>
          <a href="{% url 'web:exercises' %}">Exercises</a>
          <a href="{% url 'web:games' %}">Games</a>
          <a href="{% url 'web:community' %}">Community</a>
          <a href="{% url 'web:tools' %}">Tools</a>
      </div>
  </div>
    <section class="game">
        <section class="wrapper">
            <h1>Here Games !</h1>
            <div class="grid" id="gamesContainer">
              {% for game in contents %}
                <a href="{% url 'web:game' game.name|urlencode %}" class="game-card" data-name="{{ game.name|lower }}">
                    <img src="{{game.image.url}}" alt=""/>
                    <h3>{{game.name}}</h3>
                    <h4>{{game.get_type_display}}</h4>
                </a>
              {% endfor %}
            </div>
        </section>
    </section>
    <footer class="footer">
        <div class="footer-container">
          
          <!-- Branding -->
          <div class="footer-section">
            <img src="{% static './images/logo-text.png' %}" alt=""/>
            <p class="footer-description">
              Explore fun math games, in-depth documentation, interactive exercises, powerful tools, and a friendly community — all in one place.
            </p>
          </div>
    
          <!-- Explore -->
          <div class="footer-section">
            <h3>Explore</h3>
            <ul>
              <li><a href="{% url 'web:games' %}">Math Games</a></li>
              <li><a href="{% url 'web:documentation' %}">Documentation</a></li>
              <li><a href="{% url 'web:exercises' %}">Exercises</a></li>
              <li><a href="{% url 'web:tools' %}">Tools</a></li>
              <li><a href="{% url 'web:community' %}">Community</a></li>
            </ul>
          </div>
    
          <!-- Resources -->
          <div class="footer-section">
            <h3>Resources</h3>
            <ul>
                <li><a href="{% url 'web:index' %}">FAQ</a></li>
                <li><a href="">Contact</a></li>
            </ul>
          </div>
    
          <!-- Connect -->
          <div class="footer-section">
            <h3>Connect</h3>
            <p>Address: Nafil Manzil / Mekkone / Kottamkara / Chandanathope P.O. / Kollam-691014 / Kerala / India</p>
            <p>Email: nafilmnytfj@gmail.com</p>
            <p>Phone Number: +91 9544758339</p>
          </div>
        </div>
        <div class="footer-bottom">
          &copy; 2025 Mathbox. All rights reserved.
        </div>
    </footer>  
</body>
</html>

Mathbox/templates/tools.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{% static './images/favicon.ico' %}"/>
    <title>MathBox-tools</title>
    <link rel="stylesheet" href="{% static './css/style.css' %}">
    <script src="{% static './js/script.js' %}" defer></script>
</head>
<body>
    <header>
      <img src="{% static './images/menu.svg' %}" alt="" id="menu"/>
        <h1>
            <a href="#">
                <img src="{% static './images/logo-text.svg' %}" alt=""/>
            </a>
        </h1>
        <nav>
            <ul>
                <li><a href="{% url 'web:index' %}">Home</a></li>
                <li><a href="{% url 'web:documentation' %}">Documentation</a></li>
                <li><a href="{% url 'web:exercises' %}">Exercises</a></li>
                <li><a href="{% url 'web:games' %}">Games</a></li>
                <li><a href="{% url 'web:community' %}">Community</a></li>
                <li><a href="{% url 'web:tools' %}">Tools</a></li>
            </ul>
        </nav>
        <ul>
            <li>
                <div class="form">
                    <input type="search" placeholder="Search Tools..." id="toolsSearch"/>
                    <img src="{% static './images/search.svg' %}" alt=""/>
                </div>
            </li>
        </ul>
    </header>
    <div id="nav" class="overlay">
      <a href="javascript:void(0)" class="closebtn" id="close">&times;</a>
      <div class="overlay-content">
          <a href="{% url 'web:index' %}">Home</a>
          <a href="{% url 'web:documentation' %}">Documentation</a>
          <a href="{% url 'web:exercises' %}">Exercises</a>
          <a href="{% url 'web:games' %}">Games</a>
          <a href="{% url 'web:community' %}">Community</a>
          <a href="{% url 'web:tools' %}">Tools</a>
      </div>
  </div>
    <section class="list">
        <section class="wrapper">
            <h1>Here Tools !</h1>
            <div class="flex" id="toolsContainer">
              {% for tool in contents %}
                <a href="{% url 'web:tool' tool.name|urlencode %}" class="tool-card" style="justify-content: center;" data-name="{{ tool.name|lower }}">
                    <h3 style="font-size: 39px;color: #fff;margin-right: 13px;">To Calculate</h3>
                    <h3 style="font-size: 39px;color: teal;">{{tool.name}}</h3>
                </a>
              {% endfor %}
            </div>
        </section>
    </section>
    <footer class="footer">
        <div class="footer-container">
          
          <!-- Branding -->
          <div class="footer-section">
            <img src="{% static './images/logo-text.png' %}" alt=""/>
            <p class="footer-description">
              Explore fun math games, in-depth documentation, interactive exercises, powerful tools, and a friendly community — all in one place.
            </p>
          </div>
    
          <!-- Explore -->
          <div class="footer-section">
            <h3>Explore</h3>
            <ul>
              <li><a href="{% url 'web:games' %}">Math Games</a></li>
              <li><a href="{% url 'web:documentation' %}">Documentation</a></li>
              <li><a href="{% url 'web:exercises' %}">Exercises</a></li>
              <li><a href="{% url 'web:tools' %}">Tools</a></li>
              <li><a href="{% url 'web:community' %}">Community</a></li>
            </ul>
          </div>
    
          <!-- Resources -->
          <div class="footer-section">
            <h3>Resources</h3>
            <ul>
                <li><a href="{% url 'web:index' %}">FAQ</a></li>
                <li><a href="">Contact</a></li>
            </ul>
          </div>
    
          <!-- Connect -->
          <div class="footer-section">
            <h3>Connect</h3>
            <p>Address: Nafil Manzil / Mekkone / Kottamkara / Chandanathope P.O. / Kollam-691014 / Kerala / India</p>
            <p>Email: nafilmnytfj@gmail.com</p>
            <p>Phone Number: +91 9544758339</p>
          </div>
        </div>
        <div class="footer-bottom">
          &copy; 2025 Mathbox. All rights reserved.
        </div>
      </footer>
</body>
</html>